build: false
version: 2.3.1.{build}-{branch}
platform: x64

environment:
  matrix:
    - PYTHON: 2.7
      CONDA: "C:\\Miniconda-x64"

    - PYTHON: 3.6
      CONDA: "C:\\Miniconda36-x64"

install:
  - set PATH=%CONDA%;%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install python=%PYTHON% numpy scipy=1.0.1 mkl==2018.0.2 nose sphinx mock pip --quiet
  - pip install matplotlib
  - pip install git+https://github.com/OpenMDAO/testflo.git
  - cd C:\projects\blue*
  - pip install -e .
  - pip list
  - conda list

test_script:
  - testflo . -n 1
